version: '3'
services:
  sql:
    image: mysql:8.0.32
    container_name: openreads-sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=topsecretpassword
  elastic:
    image: elasticsearch:8.5.3
    container_name: openreads-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
  redis:
    image: redis:7.0.6
    container_name: openreads-redis
    ports:
      - "6379:6379"
  auth:
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: openreads-keycloak
    ports:
      - "9001:8080"
    command: start --auto-build --cache=local --http-enabled=true --hostname-strict=false --hostname-strict-https=false
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
