name: mobile
description: "Open Reads - Book tracking and social reading platform"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.4
  provider: ^6.1.1
  equatable: ^2.0.5

  dio: ^5.4.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1

  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^9.0.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  bloc_test: ^9.1.6
  mockito: ^5.4.4

flutter:
  uses-material-design: true
