spring:
  datasource:
    url: jdbc:mysql://localhost:3306/open-reads
    username: root
    password: topsecretpassword
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

open-reads:
  redis:
    endpoint: localhost:6379
    cachePrefix: open-reads

springdoc:
  api-docs:
    enabled: true
