spring:
  datasource:
    url: jdbc:mysql://localhost:3306/open-reads
    username: root
    password: topsecretpassword
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      connection-url: jdbc:mysql://localhost:3306/open-reads
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: open-reads
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
            keycloak:
                issuer-uri: http://localhost:9001/realms/open-reads
                user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001/realms/open-reads

open-reads:
  redis:
    endpoint: localhost:6379
    cachePrefix: open-reads

springdoc:
  api-docs:
    enabled: true
